"""empty message

Revision ID: 55098703db89
Revises: 
Create Date: 2024-08-27 09:54:43.824348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55098703db89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('book', sa.String(length=50), nullable=False),
    sa.Column('abb', sa.String(length=10), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verse', sa.Integer(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', text)", persisted=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bible', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bible_book'), ['book'], unique=False)
        batch_op.create_index('ix_bible_book_chapter_verse', ['book', 'chapter', 'verse'], unique=False)
        batch_op.create_index('ix_bible_search_vector', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_bible_verse_id'), ['verse_id'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('verse_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['verse_id'], ['bible.verse_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note')
    op.drop_table('users')
    with op.batch_alter_table('bible', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bible_verse_id'))
        batch_op.drop_index('ix_bible_search_vector', postgresql_using='gin')
        batch_op.drop_index('ix_bible_book_chapter_verse')
        batch_op.drop_index(batch_op.f('ix_bible_book'))

    op.drop_table('bible')
    # ### end Alembic commands ###
