"""empty message

Revision ID: ba1d61beed32
Revises: 7c3ff64b0c9e
Create Date: 2024-08-17 14:22:27.159738

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba1d61beed32'
down_revision = '7c3ff64b0c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bible')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('book', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('abb', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('chapter', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('verse', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('search_index', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='bible_pkey')
    )
    # ### end Alembic commands ###
